<?php linkJS("assets/plugins/bootstrap/js/bootstrap.min.js");?>
<?php linkJS("assets/plugins/bootstrap/js/bootstrap.min.js"); ?>
<?php linkJS("assets/js/vendors/jquery.sparkline.min.js"); ?>
<?php linkJS("assets/js/vendors/circle-progress.min.js"); ?>
<?php linkJS("assets/plugins/rating/jquery.rating-stars.js"); ?>
<?php linkJS("assets/plugins/moment/moment.min.js"); ?>
<?php linkJS("assets/plugins/bootstrap-daterangepicker/daterangepicker.js"); ?>
<?php linkJS("assets/plugins/toggle-sidebar/sidemenu.js"); ?>
<?php linkJS("assets/plugins/accordion1/js/easyResponsiveTabs.js"); ?>
<?php linkJS("assets/plugins/scroll-bar/jquery.mCustomScrollbar.concat.min.js"); ?>
<?php linkJS("assets/plugins/sidebar/sidebar.js"); ?>
<?php linkJS("assets/plugins/fileuploads/js/dropify.js"); ?>
<?php linkJS("assets/plugins/fileuploads/js/dropify-demo.js"); ?>
<?php linkJS("assets/plugins/select2/select2.full.min.js"); ?>
<?php linkJS("assets/js/select2.js"); ?>
<?php linkJS("assets/plugins/counters/jquery.missofis-countdown.js"); ?>
<?php linkJS("assets/plugins/counters/counter.js"); ?>
<?php linkJS("assets/plugins/time-picker/jquery.timepicker.js"); ?>
<?php linkJS("assets/plugins/time-picker/toggles.min.js"); ?>
<?php linkJS("assets/plugins/date-picker/spectrum.js"); ?>
<?php linkJS("assets/plugins/date-picker/jquery-ui.js"); ?>
<?php linkJS("assets/plugins/input-mask/jquery.maskedinput.js"); ?>
<?php linkJS("assets/plugins/multipleselect/multiple-select.js"); ?>
<?php linkJS("assets/plugins/multipleselect/multi-select.js"); ?>
<?php linkJS("assets/js/custom.js"); ?>
